CREATE TABLE [dbo].[Corte]
(
    [Id] BIGINT IDENTITY (1, 1) NOT NULL,
    [EmpresaId] BIGINT NOT NULL,
    [SucursalId] BIGINT NOT NULL,
    [UsuarioId] BIGINT NOT NULL,
    [CajaChicaId] BIGINT NOT NULL,
    [FechaCorte] DATETIME CONSTRAINT [DF_Corte_FechaCorte] DEFAULT (GETDATE()) NOT NULL,
    [MontoInicial] DECIMAL (18, 4) CONSTRAINT [DF_Corte_MontoInicial] DEFAULT ((0)) NOT NULL,
    [TotalVentas] DECIMAL (18, 4) CONSTRAINT [DF_Corte_TotalVentas] DEFAULT ((0)) NOT NULL,
    [TotalEfectivo] DECIMAL (18, 4) CONSTRAINT [DF_Corte_TotalEfectivo] DEFAULT ((0)) NOT NULL,
    [TotalTarjeta] DECIMAL (18, 4) CONSTRAINT [DF_Corte_TotalTarjeta] DEFAULT ((0)) NOT NULL,
    [TotalTransferencia] DECIMAL (18, 4) CONSTRAINT [DF_Corte_TotalTransferencia] DEFAULT ((0)) NOT NULL,
    [Salidas] DECIMAL (18, 4) CONSTRAINT [DF_Corte_Salidas] DEFAULT ((0)) NOT NULL,
    [EfectivoEsperado] DECIMAL (18, 4) CONSTRAINT [DF_Corte_EfectivoEsperado] DEFAULT ((0)) NOT NULL,
    [EfectivoContado] DECIMAL (18, 4) CONSTRAINT [DF_Corte_EfectivoContado] DEFAULT ((0)) NOT NULL,
    [Diferencia] DECIMAL (18, 4) CONSTRAINT [DF_Corte_Diferencia] DEFAULT ((0)) NOT NULL,
    [Observaciones] NVARCHAR (MAX) NULL,
    [Estatus] BIT CONSTRAINT [DF_Corte_Estatus] DEFAULT ((1)) NOT NULL,
    [CreadoPor] NVARCHAR (25) NOT NULL,
    [FechaCreacion] DATETIME CONSTRAINT [DF_Corte_FechaCreacion] DEFAULT (GETDATE()) NOT NULL,
    [ModificadoPor] NVARCHAR (25) NULL,
    [FechaModificacion] DATETIME NULL,
    CONSTRAINT [PK_Corte] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Corte_Empresa] FOREIGN KEY ([EmpresaId]) REFERENCES [dbo].[Empresa] ([Id]),
    CONSTRAINT [FK_Corte_Sucursal] FOREIGN KEY ([SucursalId]) REFERENCES [dbo].[Sucursal] ([Id]),
    CONSTRAINT [FK_Corte_Usuario] FOREIGN KEY ([UsuarioId]) REFERENCES [dbo].[Usuario] ([Id]),
    CONSTRAINT [FK_Corte_CajaChica] FOREIGN KEY ([CajaChicaId]) REFERENCES [dbo].[CajaChica] ([Id])
);
